# 本地 SOCKS5 dante 配置
# 启动指令 sudo sockd -f /opt/homebrew/etc/sockd.conf
# 日志输出位置
logoutput: /tmp/sockd.log

# 内部接口：监听的网卡和端口
internal: en0 port = 1080

# 外部接口：用于出站连接的网卡（可以是虚拟的）
# VPN 接口查看指令 ifconfig | grep -A 1 utun
# VPN 的 utun4（尾部数字可不固定） 接口，当 VPN 没开启时此接口不存在，开起后的 utun4 长这个样子
# utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1460
#	inet 26.26.26.1 --> 26.26.26.53 netmask 0xfffffff8
# 能看到一个公网 IPv4 地址
external: utun4

# 认证方式：none 表示无认证，无需账号密码
socksmethod: none

# 特权用户
user.privileged: root
user.unprivileged: nobody

# 客户端访问规则：允许所有IP连接
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error connect disconnect
}

# SOCKS代理规则：允许所有请求通过
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    # udp 规则
    udp.portrange: 40000-45000
    log: error connect disconnect
}